# based on https://github.com/actions-rs/meta/blob/master/recipes/matrix.md

name: ci
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    
    name: Rust build on ${{matrix.os}}
    steps:
      - uses: actions/checkout@v1

      - uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          components: rustfmt, clippy

      - uses: actions-rs/cargo@v1
        with:
          command: build

      - uses: actions-rs/cargo@v1
        with:
          command: test

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
